itk-dev/deltag.aarhus.dk

- web/modules/custom/hoeringsportal_project_timeline/assets/js/hoeringsportal_timeline.js
- web/modules/custom/hoeringsportal_project_timeline/src/Plugin/Block/ProjectTimeline.php
- web/modules/custom/hoeringsportal_public_meeting/hoeringsportal_public_meeting.module
- web/themes/custom/hoeringsportal/templates/content/node--public-meeting--teaser.html.twig
https://jira.itkdev.dk/browse/HRIN-417
> HRIN-417: CHanged display of timeline

- config/sync/core.entity_form_display.node.public_meeting.default.yml
- config/sync/core.entity_view_display.node.public_meeting.default.yml
- config/sync/field.field.node.public_meeting.field_pretix_event_settings.yml
- config/sync/field.storage.node.field_pretix_event_settings.yml
https://jira.itkdev.dk/browse/HRIN-413
Depends on https://github.com/itk-dev/itk_pretix_d8/pull/3
> HRIN-413: Add pretix event settings field

- web/modules/custom/hoeringsportal_deskpro/hoeringsportal_deskpro.module
- web/modules/custom/hoeringsportal_deskpro/src/Controller/AutocompleteController.php
- web/modules/custom/hoeringsportal_deskpro/src/Plugin/Validation/Constraint/AgentEmailContraint.php
- web/modules/custom/hoeringsportal_deskpro/src/Plugin/Validation/Constraint/AgentEmailContraintValidator.php
https://jira.itkdev.dk/browse/HRIN-445
* Adds validation of case worker.
* Makes auto-complete handler actual work as expected
> HRIN-445: Validate hearing agent

- web/modules/custom/hoeringsportal_data/hoeringsportal_data.routing.yml
- web/modules/custom/hoeringsportal_data/src/Controller/Api/GeoJSON/PublicMeetingController.php
- web/modules/custom/hoeringsportal_data/src/Helper/GeoJsonHelper.php
https://jira.itkdev.dk/browse/HRIN-423
Adds an GeoJSON api endpoint for public meeting dates (`/api/geojson/public_meetings/dates`).
> HRIN-423: Added public meeting dates in GeoJSON api

- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/itk_pretix.pretixconfig.yml
https://jira.itkdev.dk/browse/HRIN-451
Depends on changes in https://github.com/itk-dev/itk_pretix_d8/pull/5
> HRIN-451: Config filter

- README.md
- composer.json
- composer.lock
- config/sync/config_ignore.settings.yml
- config/sync/core.extension.yml
https://jira.itkdev.dk/browse/HRIN-461
See also https://github.com/itk-dev/itk_pretix_d8/pull/10
> HRIN-461: config_ignore

- config/sync/field.storage.node.field_pretix_dates.yml
https://jira.itkdev.dk/browse/HRIN-453
Depends on changes in https://github.com/itk-dev/itk_pretix_d8/pull/9
> HRIN-453: Single date on meeting

- web/themes/custom/hoeringsportal/templates/misc/itk-pretix-date-entry.html.twig
https://jira.itkdev.dk/browse/HRIN-447
> HRIN-447: Show expired meetings

- composer.json
- config/sync/core.extension.yml
- config/sync/quick_node_clone.settings.yml
- config/sync/user.role.editor.yml
https://jira.itkdev.dk/browse/HRIN-454
Depends on changes in https://github.com/itk-dev/itk_pretix_d8/pull/8
> HRIN-454: Clone node

- config/sync/core.entity_form_display.node.public_meeting.default.yml
- web/modules/custom/hoeringsportal_public_meeting/hoeringsportal_public_meeting.module
https://jira.itkdev.dk/browse/HRIN-463
> HRIN-463: Removed references to non-existent field

- config/sync/views.view.timeline_related_items.yml
https://jira.itkdev.dk/browse/HRIN-464
> HRIN-464: Hid empty related items

- config/sync/core.extension.yml
- web/modules/custom/hoeringsportal_hearing/hoeringsportal_hearing.info.yml
- web/modules/custom/hoeringsportal_hearing/hoeringsportal_hearing.module
- web/modules/custom/hoeringsportal_hearing/hoeringsportal_hearing.services.yml
- web/modules/custom/hoeringsportal_hearing/src/EventSubscriber/EventSubscriber.php
https://jira.itkdev.dk/browse/HRIN-420
This is a hack!
> HRIN-420: Added a module with a hack

- phpcs.xml.dist
- web/modules/custom/hoeringsportal_content_access/hoeringsportal_content_access.module
- web/modules/custom/hoeringsportal_hearing/hoeringsportal_hearing.module
- web/modules/custom/hoeringsportal_public_meeting/hoeringsportal_public_meeting.module
- web/modules/custom/hoeringsportal_public_meeting/src/Helper/PublicMeetingHelper.php
- web/themes/custom/hoeringsportal/hoeringsportal.theme
- web/themes/custom/hoeringsportal/templates/field/field--field-registration-deadline.html.twig
https://jira.itkdev.dk/browse/HRIN-468
> HRIN-468: misc

- web/modules/custom/hoeringsportal_deskpro/src/Form/HearingTicketAddForm.php
https://jira.itkdev.dk/browse/DEVSUPP-212
> DEVSUPP-212: Added description to hearing form address field

- web/modules/custom/hoeringsportal_deskpro/templates/block/hoeringsportal-hearing-tickets.html.twig
https://jira.itkdev.dk/browse/DEVSUPP-211
> DEVSUPP-211: Change ticket id display

- web/themes/custom/hoeringsportal/templates/content/node--teaser.html.twig
https://jira.itkdev.dk/browse/DEVSUPP-226
> DEVSUPP-226: Change <p> to <h3> for accessibility

- web/modules/custom/hoeringsportal_public_meeting/hoeringsportal_public_meeting.module
- web/modules/custom/hoeringsportal_public_meeting/src/Helper/PublicMeetingHelper.php
- web/themes/custom/hoeringsportal/hoeringsportal.info.yml
- web/themes/custom/hoeringsportal/hoeringsportal.theme
- web/themes/custom/hoeringsportal/templates/field/field--node--field-signup-link--public-meeting.html.twig
https://jira.itkdev.dk/browse/HRIN-485
> HRIN-485: Handling of dates

- web/themes/custom/hoeringsportal/templates/field/field--field-pretix-dates.html.twig
* Fix mobile view elements not fully visible.
* Fix content alignment
> HRIN-465: Update styling. Fix mobile view.

- config/sync/core.entity_form_display.node.hearing.default.yml
- config/sync/field.field.node.hearing.field_map.yml
- web/modules/custom/hoeringsportal_data/src/Plugin/Field/FieldWidget/MapDefaultWidget.php
https://jira.itkdev.dk/browse/HRIN-523
Cherry-pick from https://github.com/itk-dev/hoeringsportal/pull/73
> HRIN-523: Made point on map required on Hearing

- web/themes/custom/hoeringsportal/templates/field/field--field-registration-deadline.html.twig
https://jira.itkdev.dk/browse/HRIN-485
> HRIN-485: Deadline display

- config/sync/core.entity_form_display.node.public_meeting.default.yml
- config/sync/core.entity_view_display.node.public_meeting.default.yml
- config/sync/core.entity_view_display.node.public_meeting.hearing_ticket_add.yml
- config/sync/core.entity_view_display.node.public_meeting.hearing_ticket_view.yml
- config/sync/core.entity_view_display.node.public_meeting.list_display.yml
- config/sync/core.entity_view_display.node.public_meeting.teaser.yml
- config/sync/field.field.node.public_meeting.field_cancelled_date.yml
- config/sync/field.field.node.public_meeting.field_cancelled_text.yml
- config/sync/field.field.node.public_meeting.field_public_meeting_cancelled.yml
- config/sync/field.storage.node.field_cancelled_date.yml
- config/sync/field.storage.node.field_cancelled_text.yml
- config/sync/field.storage.node.field_public_meeting_cancelled.yml
- web/modules/custom/hoeringsportal_content_blocks/src/Plugin/Block/MeetingWarning.php
- web/modules/custom/hoeringsportal_content_blocks/templates/hoeringsportal-meeting-warning.html.twig
- web/modules/custom/hoeringsportal_public_meeting/hoeringsportal_public_meeting.module
- web/modules/custom/hoeringsportal_public_meeting/templates/hoeringsportal-public-meeting-summary.html.twig
- web/themes/custom/hoeringsportal/templates/content/node--public-meeting--teaser.html.twig
- web/themes/custom/hoeringsportal/templates/ds/ds-2col-stacked--node-public-meeting.html.twig
- web/themes/custom/hoeringsportal/templates/field/field--field-cancelled-text.html.twig
https://jira.itkdev.dk/browse/HRIN-470
> HRIN-470: Added cancel functionality to public meeting

- web/modules/custom/hoeringsportal_project_timeline/src/Plugin/Block/ProjectTimeline.php
- web/themes/custom/hoeringsportal/templates/field/field--dynamic-block-field--node-project-timeline.html.twig
https://jira.itkdev.dk/browse/HRIN-554
> HRIN-554: Timeline display issues

- web/themes/custom/hoeringsportal/templates/field/field--field-pretix-dates.html.twig
https://jira.itkdev.dk/browse/HRIN-556
> HRIN-556: Responsive sign up

- composer.lock
- web/modules/custom/hoeringsportal_public_meeting/hoeringsportal_public_meeting.module
- web/modules/custom/hoeringsportal_public_meeting/src/Commands/DrushCommands.php
https://jira.itkdev.dk/browse/HRIN-557
> HRIN-557: Check deadline on public meetings

- config/sync/core.entity_view_display.node.public_meeting.default.yml
https://jira.itkdev.dk/browse/HRIN-497
Includes all changes done to public meeting view
> HRIN-497: Removed image from content type

- composer.lock
- config/sync/core.entity_form_display.node.public_meeting.default.yml
https://jira.itkdev.dk/browse/HRIN-485
> HRIN-485: Hid end date on pretix dates

- web/modules/custom/hoeringsportal_public_meeting/src/Plugin/Block/PublicMeetingSummaryBlock.php
- web/modules/custom/hoeringsportal_public_meeting/templates/hoeringsportal-public-meeting-summary.html.twig
https://jira.itkdev.dk/browse/HRIN-554
Fixes issue with displaying public meetings not using pretix.
> HRIN-554: Display error

- web/themes/custom/hoeringsportal/templates/content/media--content-display.html.twig
- web/themes/custom/hoeringsportal/templates/ds/ds-1col.html.twig
- web/themes/custom/hoeringsportal/templates/ds/ds-2col-stacked.html.twig
https://jira.itkdev.dk/browse/HRIN-544
> HRIN-544: Moved image wrapper

- config/sync/core.entity_view_display.node.hearing.default.yml
https://jira.itkdev.dk/browse/HRIN-525
Fix bug
> HRIN-525: Added timeline config on hearing

- config/sync/field.storage.node.field_signup_selection.yml
https://jira.itkdev.dk/browse/HRIN-558
> HRIN-558: Renamed labels

- composer.lock
- config/sync/field.field.node.public_meeting.field_pretix_dates.yml
https://jira.itkdev.dk/browse/HRIN-570
> HRIN-570: Made pretix sign-up not required

- config/sync/field.field.node.hearing.field_area.yml
- config/sync/field.field.node.public_meeting.field_area.yml
- web/modules/custom/hoeringsportal_hearing/assets/js/form.js
- web/modules/custom/hoeringsportal_hearing/hoeringsportal_hearing.libraries.yml
- web/modules/custom/hoeringsportal_hearing/hoeringsportal_hearing.module
- web/modules/custom/hoeringsportal_public_meeting/assets/js/form.js
- web/modules/custom/hoeringsportal_public_meeting/hoeringsportal_public_meeting.libraries.yml
- web/modules/custom/hoeringsportal_public_meeting/hoeringsportal_public_meeting.module
https://jira.itkdev.dk/browse/HRIN-567
Adds “Select all“/“Select none” buttons to “Area” on hearings and public meetings.
> HRIN-567: Select all areas

- web/themes/custom/hoeringsportal/templates/field/field--field-pretix-dates.html.twig
https://jira.itkdev.dk/browse/HRIN-566
Fix width issue on signup table
> HRIN-565: Set back to original display type

- composer.lock
- web/modules/custom/hoeringsportal_public_meeting/src/Helper/PublicMeetingHelper.php
- web/themes/custom/hoeringsportal/hoeringsportal.theme
- web/themes/custom/hoeringsportal/templates/field/field--dynamic-block-field--node-public-meeting-summary.html.twig
- web/themes/custom/hoeringsportal/templates/field/field--field-pretix-dates.html.twig
- web/themes/custom/hoeringsportal/templates/misc/itk-pretix-date-entry.html.twig
https://jira.itkdev.dk/browse/HRIN-572
> HRIN-572: Hotfixes

- web/modules/custom/hoeringsportal_data/src/Controller/Api/DefaultController.php
- web/modules/custom/hoeringsportal_data/src/Helper/GeoJsonHelper.php
- web/themes/custom/hoeringsportal/assets/images/maps/hearing-icon-selected.svg
- web/themes/custom/hoeringsportal/assets/images/maps/hearing-icon.svg
- web/themes/custom/hoeringsportal/assets/images/maps/public-meeting-icon-selected.svg
- web/themes/custom/hoeringsportal/assets/images/maps/public-meeting-icon.svg
https://jira.itkdev.dk/browse/HRIN-578
> HRIN-578: api public meeting

- composer.lock
https://jira.itkdev.dk/browse/DEVSUPP-305
> DEVSUPP-305: Updated pretix module

- web/modules/custom/hoeringsportal_public_meeting/src/Helper/PublicMeetingHelper.php
- web/modules/custom/hoeringsportal_public_meeting/src/Plugin/Block/PublicMeetingSummaryBlock.php
https://jira.itkdev.dk/browse/DEVSUPP-329
> DEVSUPP-329: Hid registration deadline when sign-up is hidden

- web/modules/custom/hoeringsportal_public_meeting/templates/hoeringsportal-public-meeting-summary.html.twig
https://jira.itkdev.dk/browse/DEVSUPP-330
> DEVSUPP-330: Fixed issue with display of undefined date and time

- web/modules/custom/hoeringsportal_public_meeting/templates/hoeringsportal-public-meeting-summary.html.twig
- web/themes/custom/hoeringsportal/.gitignore
- web/themes/custom/hoeringsportal/.npmrc.install
- web/themes/custom/hoeringsportal/README.md
- web/themes/custom/hoeringsportal/templates/field/field--field-pretix-dates.html.twig
https://jira.itkdev.dk/browse/DEVSUPP-333
> DEVSUPP-333: Added display of address

- web/modules/custom/hoeringsportal_deskpro/src/Form/HearingTicketAddForm.php
https://jira.itkdev.dk/browse/HRIN-600
> HRIN-600: Made address fields required in hearing reply

- README.md
- composer.json
- composer.lock
- translations/custom-translations.da.po
- web/modules/custom/hoeringsportal_deskpro/src/Form/HearingTicketAddForm.php
https://jira.itkdev.dk/browse/HRIN-600
* Updates `drush`
* Updates translations – and documents how to do it.
> HRIN-600: Updated Danish translations

- composer.lock
- web/modules/custom/hoeringsportal_public_meeting/hoeringsportal_public_meeting.module
- web/modules/custom/hoeringsportal_public_meeting/hoeringsportal_public_meeting.services.yml
- web/modules/custom/hoeringsportal_public_meeting/src/Commands/DrushCommands.php
- web/modules/custom/hoeringsportal_public_meeting/src/Helper/PublicMeetingHelper.php
https://jira.itkdev.dk/browse/DEVSUPP-351
Sets deadline as end of presale in pretix.
Depends on changes in https://github.com/itk-dev/itk_pretix_d8/pull/27.
> DEVSUPP-351: Used deadline as end of presale in pretix

- web/modules/custom/hoeringsportal_config_settings/src/Form/ItkGeneralSettingsForm.php
- web/modules/custom/hoeringsportal_forms/hoeringsportal_forms.module
https://jira.itkdev.dk/browse/HRIN-608
> HRIN-608: Login message

- web/modules/custom/hoeringsportal_forms/hoeringsportal_forms.libraries.yml
- web/modules/custom/hoeringsportal_forms/js/user-login-form.js
https://jira.itkdev.dk/browse/HRIN-609
> HRIN-609: Keep fragment id in login form

- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/field.field.node.hearing.field_area.yml
- config/sync/field.field.node.project.field_timeline_items.yml
- config/sync/field.field.node.public_meeting.field_area.yml
- config/sync/field.field.node.public_meeting.field_section.yml
- config/sync/language.content_settings.redirect.redirect.yml
- config/sync/node.type.public_meeting.yml
- config/sync/redirect.settings.yml
- config/sync/system.action.redirect_delete_action.yml
- config/sync/views.view.all_meetings.yml
- config/sync/views.view.redirect.yml
- web/themes/custom/hoeringsportal/hoeringsportal.theme
https://jira.itkdev.dk/browse/HRIN-612 https://jira.itkdev.dk/browse/HRIN-613
> Rename borgermøde to begivenhed. Rename type.

- config/sync/core.entity_view_display.node.public_meeting.default.yml
- config/sync/field.field.node.public_meeting.field_contact.yml
- web/themes/custom/hoeringsportal/templates/field/field--dynamic-block-field--node-public-meeting-summary.html.twig
https://jira.itkdev.dk/browse/SUPP0RT-152
Adds display of “Kontakt” to “Begivenhed”
> SUPP0RT-152: Added “Kontakt” to display of Event

- web/modules/custom/hoeringsportal_public_meeting/hoeringsportal_public_meeting.services.yml
- web/modules/custom/hoeringsportal_public_meeting/src/EventSubscriber/EventSubscriber.php
https://jira.itkdev.dk/browse/HRIN-622
> HRIN-622: Changed default sorting of completed events

- .gitignore
- README.md
- composer.json
- composer.lock
- docker-compose.yml
- web/.gitignore
- web/.htaccess
- web/modules/.gitignore
- web/profiles/.gitignore
- web/sites/.gitignore
- web/sites/default/default.settings.php
- web/sites/example.settings.local.php
- web/themes/.gitignore
- SERV-234: Updated composer packages
- SERV-234: Updated to Drupal core 8.9
- SERV-234: Updated to composer 2
> SERV-234: Security update

- config/sync/views.view.user_admin_people.yml
https://jira.itkdev.dk/browse/HRIN-625
Adds query parameters on export redirect.
> HRIN-625: Include query params in export redirect

- composer.lock
- config/sync/core.entity_form_display.node.public_meeting.default.yml
- config/sync/core.entity_view_display.node.public_meeting.default.yml
- config/sync/core.entity_view_display.node.public_meeting.hearing_ticket_add.yml
- config/sync/core.entity_view_display.node.public_meeting.hearing_ticket_view.yml
- config/sync/core.entity_view_display.node.public_meeting.list_display.yml
- config/sync/core.entity_view_display.node.public_meeting.teaser.yml
- config/sync/field.field.node.public_meeting.field_email_address.yml
- config/sync/field.storage.node.field_email_address.yml
https://jira.itkdev.dk/browse/HRIN-621
- HRIN-621: Added contact email on event
- HRIN-621: Update itk_pretix module
> HRIN-621: Contact email on event

- config/sync/core.entity_view_display.node.public_meeting.list_display.yml
https://jira.itkdev.dk/browse/SUPP0RT-245
> SUPP0RT-245: Changed list display for public meeting

- config/sync/core.entity_view_display.node.public_meeting.default.yml
https://jira.itkdev.dk/browse/SUPP0RT-277
Fixes issue with buggy field:
> Support-277: Hid date field from public meeting

- composer.lock
https://jira.itkdev.dk/browse/HRIN-637
Applies bug fix update to `samlauth` module.
> HRIN-637: Updated to samlauth 3.2.0

- config/sync/samlauth.authentication.yml
https://jira.itkdev.dk/browse/HRIN-647
Fixes issues with users not being able to sign in with SAML.
> HRIN-647: Tweaked samlauth config to allow user mapping

- config/sync/core.entity_form_display.node.hearing.default.yml
- config/sync/core.entity_view_display.node.hearing.default.yml
https://jira.itkdev.dk/browse/SUPP0RT-309
> SUPP0RT-309: Hid hearing tags from form and display views

- config/sync/field.field.node.public_meeting.field_contact.yml
https://jira.itkdev.dk/browse/SUPP0RT-308
> SUPP0RT-308: Made "Kontakt" on "Begivenhed" optional

- web/modules/custom/hoeringsportal_public_meeting/assets/js/form.js
https://jira.itkdev.dk/browse/SUPP0RT-306
> SUPP0RT-306: Removed Select all/none buttons. Emphasized "Hele kommunen".

- web/modules/custom/hoeringsportal_data/README.md
- web/modules/custom/hoeringsportal_data/hoeringsportal_data.routing.yml
- web/modules/custom/hoeringsportal_data/src/Controller/Api/DefaultController.php
- web/modules/custom/hoeringsportal_data/src/Controller/Api/V2/GeoJSON/HearingController.php
- web/modules/custom/hoeringsportal_data/src/Helper/GeoJsonHelper.php
https://jira.itkdev.dk/browse/HRIN-654
Adds a paginated GeoJSON api for hearings.
> HRIN-654: GeoJSON API v2

- docker-compose.server.yml
https://jira.itkdev.dk/browse/HRIN-659
> HRIN-659: Added server compose file

- composer.json
- composer.lock
https://jira.itkdev.dk/browse/HRIN-659
- Make upgrade status a dev package
- Remove outdated patches
> HRIN-659: Moved upgradge status

- web/themes/custom/hoeringsportal/templates/newsletter-bottom-link.html.twig
https://jira.itkdev.dk/browse/HRIN-658
Changes after consulting with designer.
> HRIN-658: Updated message and link text

- web/themes/custom/hoeringsportal/templates/layout/region--header.html.twig
The status messages was not displayed.
> Added status messages to header template

- web/modules/custom/hoeringsportal_deskpro/src/Service/DeskproService.php
https://jira.itkdev.dk/browse/HRIN-671
> Added Deskpro client logger

- composer.json
- composer.lock
- docker-compose.server.yml
- web/modules/custom/hoeringsportal_deskpro/README.md
- web/modules/custom/hoeringsportal_deskpro/composer.json
- web/modules/custom/hoeringsportal_deskpro/hoeringsportal_deskpro.routing.yml
- web/modules/custom/hoeringsportal_deskpro/src/Commands/DrushCommands.php
- web/modules/custom/hoeringsportal_deskpro/src/Controller/DataController.php
- web/modules/custom/hoeringsportal_deskpro/src/Plugin/AdvancedQueue/JobType/SynchronizeTicket.php
- web/modules/custom/hoeringsportal_deskpro/src/Service/HearingHelper.php
- web/modules/custom/hoeringsportal_deskpro/templates/block/hoeringsportal-hearing-ticket.html.twig
- web/modules/custom/hoeringsportal_deskpro/templates/block/hoeringsportal-hearing-tickets.html.twig
https://jira.itkdev.dk/browse/HRIN-672
Adds endpoint for synchronizing just a single ticket (rather that all tickets on the hearing).
> HRIN-672: Added ticket synchonization

- web/modules/custom/hoeringsportal_data/hoeringsportal_data.module
https://jira.itkdev.dk/browse/HRIN-671
See https://www.drupal.org/project/drupal/issues/2852657#comment-14151263
> HRIN-671: Fixed redirect issue

- web/modules/custom/hoeringsportal_data/src/Controller/MapsController.php
- web/modules/custom/hoeringsportal_deskpro/src/Service/HearingHelper.php
- web/themes/custom/hoeringsportal/hoeringsportal.theme
https://jira.itkdev.dk/browse/HRIN-671
Applies coding standards.
> HRIN-671: Applied coding standards

- README.md
- composer.json
- Updated readme
- Updated composer.json
> Updated readme

- config/sync/core.entity_form_display.node.hearing.default.yml
- config/sync/core.entity_view_display.node.hearing.default.yml
- config/sync/core.entity_view_display.node.hearing.hearing_ticket_add.yml
- config/sync/core.entity_view_display.node.hearing.hearing_ticket_view.yml
- config/sync/core.entity_view_display.node.hearing.list_display.yml
- config/sync/core.entity_view_display.node.hearing.teaser.yml
- config/sync/field.field.node.hearing.field_getorganized_case_id.yml
- config/sync/field.storage.node.field_getorganized_case_id.yml
- web/modules/custom/hoeringsportal_deskpro/src/Service/HearingHelper.php
- web/modules/custom/hoeringsportal_deskpro/src/State/DeskproConfig.php
- web/modules/custom/hoeringsportal_forms/templates/hoeringsportal-hearing-node-form.html.twig
https://jira.itkdev.dk/browse/HRIN-681
Adds and handles GetOrganized case id field on hearing.
> Add GetOrganized case id on hearing

- composer.json
- composer.lock
- config/sync/core.entity_form_display.node.landing_page.default.yml
- config/sync/core.entity_form_display.node.page_map.default.yml
- config/sync/core.entity_form_display.node.static_page.default.yml
- config/sync/core.entity_view_display.node.hearing.default.yml
- config/sync/core.entity_view_display.node.landing_page.default.yml
- config/sync/core.entity_view_display.node.page_map.default.yml
- config/sync/core.entity_view_display.node.project.default.yml
- config/sync/core.entity_view_display.node.public_meeting.default.yml
- config/sync/core.entity_view_display.node.static_page.default.yml
- config/sync/core.extension.yml
- config/sync/views.view.heyloyalty_feed.yml
https://jira.itkdev.dk/browse/SUPP0RT-673
- SUPP0RT-673: Added publication date to content
- SUPP0RT-673: Updated feed to use publication date
> SUPP0RT-673: Publication date in feed

- config/sync/field.field.node.hearing.field_edoc_casefile_id.yml
[https://jira.itkdev.dk/browse/HRIN-720](https://jira.itkdev.dk/browse/HRIN-720)
Changed field to 'not required'
> HRIN-270: Update field.field.node.hearing.field_edoc_casefile_id.yml

- web/themes/custom/hoeringsportal/assets/js/hoeringsportal.js
[SUPP0RT-762](https://jira.itkdev.dk/browse/SUPP0RT-762)
Add map display to hearings
> SUPP0RT-762: Added map js

- web/sites/default/settings.php
Moves default settings above local settings.
> Moved default settings above local settings

- CHANGELOG.md
- config/sync/core.extension.yml
- config/sync/hoeringsportal_citizen_proposal.settings.yml
- config/sync/openid_connect.client.citizen_authentification.yml
- docker-compose.override.yml
- web/modules/custom/hoeringsportal_citizen_proposal/config/install/hoeringsportal_citizen_proposal.settings.yml
- web/modules/custom/hoeringsportal_citizen_proposal/hoeringsportal_citizen_proposal.routing.yml
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalAdminForm.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormAdd.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormApprove.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormBase.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Helper/Helper.php
- web/modules/custom/hoeringsportal_openid_connect/README.md
- web/modules/custom/hoeringsportal_openid_connect/hoeringsportal_openid_connect.info.yml
- web/modules/custom/hoeringsportal_openid_connect/hoeringsportal_openid_connect.module
- web/modules/custom/hoeringsportal_openid_connect/hoeringsportal_openid_connect.routing.yml
- web/modules/custom/hoeringsportal_openid_connect/hoeringsportal_openid_connect.services.yml
- web/modules/custom/hoeringsportal_openid_connect/src/Controller/OpenIDConnectRedirectController.php
- web/modules/custom/hoeringsportal_openid_connect/src/Helper.php
- web/modules/custom/hoeringsportal_openid_connect/src/Plugin/OpenIDConnectClient/OpenIDConnectCitizenClient.php
https://jira.itkdev.dk/browse/FORSLAG-35
- FORSLAG-35: Added test OIDC IdP
- FORSLAG-35: Added custom OIDC module
- FORSLAG-35: Enabled custom OIDC module
- FORSLAG-35: Handled authentication in proposal form
> Citizen authentication

- CHANGELOG.md
- web/modules/custom/hoeringsportal_citizen_proposal/config/install/hoeringsportal_citizen_proposal.settings.yml
- web/modules/custom/hoeringsportal_citizen_proposal/hoeringsportal_citizen_proposal.routing.yml
- web/modules/custom/hoeringsportal_citizen_proposal/hoeringsportal_citizen_proposal.services.yml
- web/modules/custom/hoeringsportal_citizen_proposal/src/Exception/RuntimeException.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalAdminForm.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormAdd.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormApprove.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormBase.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormSupport.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Helper/Helper.php
https://jira.itkdev.dk/browse/FORSLAG-34
Adds user authentification on support proposal form.
> User authentification on support proposal form

- composer.json
- composer.lock
- config/sync/core.extension.yml
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalAdminForm.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormAdd.php
- web/themes/custom/hoeringsportal/assets/css/module/_proposal.scss
https://jira.itkdev.dk/browse/FORSLAG-30
- Add configurable maxlength to form
> Add max lngth module and apply to proposal add form

- CHANGELOG.md
- web/modules/custom/hoeringsportal_public_meeting/src/Helper/PublicMeetingHelper.php
https://jira.itkdev.dk/browse/HRIN-734
> Fixes after upgrade test

- .github/workflows/pr.yaml
Fixes and enables `coding-standards-custom-themes` workflow job. The change log has not been updated and _will_ not be updated in this pull request.
> Update GitHub Actions job

- .docker/vhost.conf
- CHANGELOG.md
- docker-compose.server.override.yml
https://jira.itkdev.dk/browse/HRIN-745
> HRIN-745: Allowed uploading yuge files

- CHANGELOG.md
> Release 3.0.2

- CHANGELOG.md
- config/sync/hoeringsportal_citizen_proposal.settings.yml
- docker-compose.override.yml
- web/modules/custom/hoeringsportal_citizen_proposal/config/install/hoeringsportal_citizen_proposal.settings.yml
- web/modules/custom/hoeringsportal_citizen_proposal/hoeringsportal_citizen_proposal.install
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormBase.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Helper/Helper.php
https://jira.itkdev.dk/browse/FORSLAG-34
Stores hashed citizen identifier in database.
> Store hashed citizen identifier

- .github/workflows/pr.yaml
- docker-compose.override.yml
- docker-compose.yml
- documentation/Testing.md
- documentation/localDevelopment.md
- package.json
- playwright/citizen-proposal.spec.js
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormAdd.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormApprove.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormBase.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormSupport.php
- yarn.lock
* Optimizes docker compose setup by adding [profiles](https://docs.docker.com/compose/profiles/) to containers we rarely need.
* Cleans up handling of “admin messages”
* Fixes Playwright tests
> docker compose optimization

- .github/workflows/pr.yaml
- config/sync/core.entity_view_display.node.hearing.default.yml
- config/sync/core.entity_view_display.node.hearing.hearing_ticket_add.yml
- config/sync/core.entity_view_display.node.hearing.hearing_ticket_view.yml
- config/sync/core.entity_view_display.node.hearing.list_display.yml
- config/sync/core.entity_view_display.node.hearing.teaser.yml
- config/sync/core.entity_view_display.node.landing_page.default.yml
- config/sync/core.entity_view_display.node.landing_page.list_display.yml
- config/sync/core.entity_view_display.node.landing_page.teaser.yml
- config/sync/core.entity_view_display.node.page_map.default.yml
- config/sync/core.entity_view_display.node.page_map.teaser.yml
- config/sync/core.entity_view_display.node.project.default.yml
- config/sync/core.entity_view_display.node.project.list_display.yml
- config/sync/core.entity_view_display.node.project.teaser.yml
- config/sync/core.entity_view_display.node.public_meeting.default.yml
- config/sync/core.entity_view_display.node.public_meeting.hearing_ticket_add.yml
- config/sync/core.entity_view_display.node.public_meeting.hearing_ticket_view.yml
- config/sync/core.entity_view_display.node.public_meeting.list_display.yml
- config/sync/core.entity_view_display.node.public_meeting.teaser.yml
- config/sync/core.entity_view_display.node.static_page.default.yml
- config/sync/core.entity_view_display.node.static_page.list_display.yml
- config/sync/core.entity_view_display.node.static_page.teaser.yml
- config/sync/hoeringsportal_citizen_proposal.settings.yml
- Cleans up config
- Adds automatic check for config being up to date
> Config cleanup

- CHANGELOG.md
- composer.json
- composer.lock
- config/sync/user.role.citizen_proposal_editor.yml
- web/modules/custom/hoeringsportal_citizen_proposal/hoeringsportal_citizen_proposal.permissions.yml
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormBase.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormSupport.php
https://jira.itkdev.dk/browse/FORSLAG-34
Lets editors support proposals on behalf of citizens.
> Let proposal editors support on behalf of citizen

- CHANGELOG.md
- composer.json
- composer.lock
- web/themes/custom/hoeringsportal/assets/css/layout/_page-map.scss
- web/themes/custom/hoeringsportal/assets/js/show-map.js
Release 3.1.0: Citizen proposal
> Release 3.1.0

- CHANGELOG.md
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalAdminForm.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormAdd.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormApprove.php
https://jira.itkdev.dk/browse/FORSLAG-77
Adds checkbox for acception personal data storage when creating proposal.
> FORSLAG-77: Added data storage consent checkbox

- CHANGELOG.md
- config/sync/symfony_mailer.mailer_transport.smtp.yml
- docker-compose.dev.yml
- docker-compose.yml
- web/modules/custom/hoeringsportal_citizen_proposal/README.md
- web/themes/custom/hoeringsportal/templates/email/citizen-proposal/email-wrap--hoeringsportal-citizen-proposal.html.twig
https://jira.itkdev.dk/browse/FORSLAG-74
> Citizen proposal notification mails

- CHANGELOG.md
- documentation/Testing.md
- playwright/citizen-proposal-support.spec.js
- playwright/citizen-proposal.spec.js
- web/modules/custom/hoeringsportal_citizen_proposal/modules/hoeringsportal_citizen_proposal_fixtures/src/Fixture/CitizenProposalFixture.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormApprove.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormBase.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormSupport.php
https://jira.itkdev.dk/browse/FORSLAG-80
- FORSLAG-80: De-authenticated citizen after creating or supporting proposal
- FORSLAG-80: Updated Playwright test
> Citizen sign out

- CHANGELOG.md
- config/sync/core.entity_view_display.node.citizen_proposal.teaser.yml
- config/sync/core.entity_view_display.node.hearing.teaser.yml
- config/sync/core.entity_view_display.node.landing_page.default.yml
- config/sync/core.entity_view_display.node.page_map.teaser.yml
- config/sync/core.entity_view_display.node.project.teaser.yml
- config/sync/core.entity_view_display.node.public_meeting.default.yml
- config/sync/core.entity_view_display.node.public_meeting.list_display.yml
- config/sync/core.entity_view_display.node.public_meeting.teaser.yml
- config/sync/core.entity_view_display.node.static_page.default.yml
- config/sync/core.entity_view_display.node.static_page.list_display.yml
- config/sync/core.entity_view_display.node.static_page.teaser.yml
https://jira.itkdev.dk/browse/FORSLAG-90
- FORSLAG-90: Hid sharing buttons on all content types but citizen proposal
- FORSLAG-90: Hid changed date on static page
> Hide changed date on static page

- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormApprove.php
https://jira.itkdev.dk/browse/FORSLAG-77
Fixed handling of disabled checkbox value.
Accessibility-wise, it may be better to just remove the checkbox on the approval form …
> FORSLAG-77: Fixed handling of consent on approve form

- .docker/data/.gitignore
- docker-compose.dev.yml
- docker-compose.override.yml
- docker-compose.redirect.yml
- docker-compose.server.yml
- docker-compose.yml
Updates the docker compose setup, but does not update the change log.
> Updated docker compose setup

- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormBase.php
https://jira.itkdev.dk/browse/FORSLAG-80
This bugfix is not worthy of a change log entry.
> FORSLAG-80: Prevented signing out editor

- CHANGELOG.md
- web/themes/custom/hoeringsportal/templates/ds/ds-2col-stacked--node-citizen-proposal.html.twig
https://jira.itkdev.dk/browse/FORSLAG-88
I'm not sure this is a good idea and the right way to do – neither technically or accessibility wise. But it's what the customer wants.
> FORSLAG-88: Re-added and hid link button

- CHANGELOG.md
- composer.json
- composer.lock
- config/sync/core.entity_form_display.node.citizen_proposal.default.yml
- config/sync/core.extension.yml
- config/sync/editor.editor.citizen_proposal_content.yml
- config/sync/field.field.node.citizen_proposal.field_more_info.yml
- config/sync/field.field.node.citizen_proposal.field_proposal.yml
- config/sync/field.field.node.citizen_proposal.field_remarks.yml
- config/sync/filter.format.citizen_proposal_content.yml
- config/sync/user.role.anonymous.yml
- config/sync/user.role.authenticated.yml
- web/modules/custom/hoeringsportal_citizen_proposal/modules/hoeringsportal_citizen_proposal_fixtures/hoeringsportal_citizen_proposal_fixtures.info.yml
- web/modules/custom/hoeringsportal_citizen_proposal/modules/hoeringsportal_citizen_proposal_fixtures/src/Fixture/CitizenProposalFixture.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormAdd.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormBase.php
https://jira.itkdev.dk/browse/FORSLAG-92
Adds simple text format used for both citizens and editors.
> FORSLAG-92: Added and used citizen proposal text format

- web/themes/custom/hoeringsportal/templates/views/views-view--all-citizen-proposals.html.twig
https://jira.itkdev.dk/browse/FORSLAG-94
> FORSLAG-94: Added missing translation filter

- CHANGELOG.md
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormAdd.php
> Release 3.2.0

- CHANGELOG.md
- composer.json
- composer.lock
- docker-compose.override.yml
- web/modules/custom/hoeringsportal_citizen_proposal/README.md
- web/modules/custom/hoeringsportal_citizen_proposal/hoeringsportal_citizen_proposal.services.yml
- web/modules/custom/hoeringsportal_citizen_proposal/src/EventSubscriber/CitizenAccessCheckEventSubscriber.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Exception/CprException.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalAdminForm.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormBase.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Helper/CitizenAccessChecker.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Helper/CprHelper.php
- web/modules/custom/hoeringsportal_openid_connect/src/Controller/OpenIDConnectController.php
- web/modules/custom/hoeringsportal_openid_connect/src/Event/AccessCheckEvent.php
https://jira.itkdev.dk/browse/FORSLAG-97
> FORSLAG-97: Added citizen access check

- CHANGELOG.md
- web/modules/custom/hoeringsportal_citizen_proposal/modules/hoeringsportal_citizen_proposal_fixtures/hoeringsportal_citizen_proposal_fixtures.services.yml
- web/modules/custom/hoeringsportal_citizen_proposal/modules/hoeringsportal_citizen_proposal_fixtures/src/Fixture/CitizenProposalFixture.php
- web/modules/custom/hoeringsportal_citizen_proposal/modules/hoeringsportal_citizen_proposal_fixtures/src/Fixture/CitizenProposalStaticPageFixture.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalAdminForm.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormApprove.php
https://jira.itkdev.dk/browse/FORSLAG-104
Adds cancel proposal redirect URL
> FORSLAG-104: Added cancel proposal redirect URL

- CHANGELOG.md
- web/modules/custom/hoeringsportal_citizen_proposal/src/Helper/WebformHelper.php
https://jira.itkdev.dk/browse/FORSLAG-107
See comment in code for details on what is going on in this pull request.
> FORSLAG-107: Fixed length of temp store key

- CHANGELOG.md
- config/sync/views.view.all_citizen_proposals.yml
- web/modules/custom/hoeringsportal_citizen_proposal/modules/hoeringsportal_citizen_proposal_fixtures/src/Fixture/CitizenProposalFixture.php
https://jira.itkdev.dk/browse/FORSLAG-106
> FORSLAG-106: Fixed sorting of citizen proposals

- CHANGELOG.md
- web/modules/custom/hoeringsportal_citizen_proposal/hoeringsportal_citizen_proposal.install
- web/modules/custom/hoeringsportal_citizen_proposal/modules/hoeringsportal_citizen_proposal_fixtures/src/Fixture/CitizenProposalFixture.php
https://jira.itkdev.dk/browse/FORSLAG-105
Allows non-ascii data in supporter name.
> FORSLAG-105: Updated storage type

- digitaliseringskataloget.dk/sf1520_4.0/PersonBaseDataExtendedService/PersonBaseDataExtendedServiceMsg.xsd
- digitaliseringskataloget.dk/sf1520_4.0/PersonBaseDataExtendedService/sp/AuthorityContext_1.xsd
- digitaliseringskataloget.dk/sf1520_4.0/PersonBaseDataExtendedService/sp/CallContext_1.xsd
- digitaliseringskataloget.dk/sf1520_4.0/PersonBaseDataExtendedService/sp/InvocationContext_1.xsd
- digitaliseringskataloget.dk/sf1520_4.0/PersonBaseDataExtendedService/sp/PNR_1.xsd
- digitaliseringskataloget.dk/sf1520_4.0/PersonBaseDataExtendedService/sp/ServiceplatformFaultMessage_1.wsdl
- digitaliseringskataloget.dk/sf1520_4.0/PersonBaseDataExtendedService/sp/ServiceplatformFault_1.xsd
- digitaliseringskataloget.dk/sf1520_4.0/PersonBaseDataExtendedService/sp/service.properties
- digitaliseringskataloget.dk/sf1520_4.0/PersonBaseDataExtendedService/wsdl/context/PersonBaseDataExtendedService.wsdl
- digitaliseringskataloget.dk/sf1520_4.0/PersonBaseDataExtendedService/wsdl/context/policies.wsdl
- digitaliseringskataloget.dk/sf1520_4.0/PersonBaseDataExtendedService/wsdl/token/PersonBaseDataExtendedService.wsdl
- digitaliseringskataloget.dk/sf1520_4.0/PersonBaseDataExtendedService/wsdl/token/policies.wsdl
- digitaliseringskataloget.dk/sf1520_4.0/PersonBaseDataExtendedService/xsd/PersonBaseDataExtendedServiceTypes.xsd
- web/modules/custom/hoeringsportal_citizen_proposal/README.md
- web/modules/custom/hoeringsportal_citizen_proposal/src/Helper/CprHelper.php
https://jira.itkdev.dk/browse/FORSLAG-97
Updates to <https://digitaliseringskataloget.dk/integration/sf1520> » PersonBaseDataExtendedService version 5.0.
> FORSLAG-97: Added CPR service stuff

- CHANGELOG.md
- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/editor.editor.filtered_html.yml
- config/sync/filter.format.filtered_html.yml
- config/sync/user.role.citizen_proposal_editor.yml
https://jira.itkdev.dk/browse/FORSLAG-108
Adds [Editor Advanced link](https://www.drupal.org/project/editor_advanced_link) to allow editors to force links to open in new tab.
> FORSLAG-108: Added and used Editor Advanced link

- CHANGELOG.md
- config/sync/field.field.node.hearing.field_contact.yml
- config/sync/field.field.node.hearing.field_description.yml
- config/sync/field.field.node.hearing.field_more_info.yml
- config/sync/field.field.node.project.field_description.yml
- config/sync/field.field.node.public_meeting.field_contact.yml
- config/sync/field.field.node.public_meeting.field_description.yml
- config/sync/field.field.node.public_meeting.field_signup_text.yml
- config/sync/field.field.node.static_page.field_sidebar.yml
- web/modules/custom/hoeringsportal_citizen_proposal_archiving/src/Archiver/GetOrganizedArchiver.php
> Release 3.5.1

- CHANGELOG.md
- web/modules/custom/hoeringsportal_citizen_proposal_archiving/src/Archiver/GetOrganizedArchiver.php
https://jira.itkdev.dk/browse/SUPP0RT-1280
Cleaned up archiving of citizen proposals.
> SUPP0RT-1280: Cleaned up archiving

- CHANGELOG.md
- config/sync/field.field.node.hearing.field_contact.yml
- config/sync/field.field.node.hearing.field_description.yml
- config/sync/field.field.node.hearing.field_more_info.yml
- config/sync/field.field.node.project.field_description.yml
- config/sync/field.field.node.public_meeting.field_contact.yml
- config/sync/field.field.node.public_meeting.field_description.yml
- config/sync/field.field.node.public_meeting.field_signup_text.yml
- config/sync/field.field.node.static_page.field_sidebar.yml
https://jira.itkdev.dk/browse/SUPP0RT-1299
Limits text formats on non-citizen proposal content.
> SUPP0RT-1299: Limited text formats on content

- CHANGELOG.md
- web/themes/custom/hoeringsportal/assets/css/module/_list.scss
https://jira.itkdev.dk/browse/SUPP0RT-1263
Result:
> SUPP0RT-1263: Fix hidden filters on mobile

- CHANGELOG.md
- config/sync/editor.editor.hearing_description.yml
- config/sync/field.field.node.hearing.field_description.yml
Release 3.6.0
The config update should have been made in https://github.com/itk-dev/hoeringsportal/pull/376, but the automated check on that pull request did not run, so the config is updated in this pull request.
> Release 3.6.0

- CHANGELOG.md
Release 4.1.0
* [PR-383](https://github.com/itk-dev/hoeringsportal/pull/383)
Added check for numbers in person name
* [PR-379](https://github.com/itk-dev/hoeringsportal/pull/379)
Disabled eDoc casefile ID field on new hearings
* [PR-378](https://github.com/itk-dev/hoeringsportal/pull/378)
New main menu, new search.
> Release 4.1.0

- CHANGELOG.md
- web/modules/custom/hoeringsportal_deskpro/src/Form/HearingTicketAddForm.php
https://leantime.itkdev.dk/#/tickets/showTicket/1024
Fixes initialization error:
```
Error: Typed property Drupal\hoeringsportal_deskpro\Form\HearingTicketAddForm::$config must not be accessed before initialization i Drupal\hoeringsportal_deskpro\Form\HearingTicketAddForm->initialize() (linje 43 af /app/web/modules/custom/hoeringsportal_deskpro/src/Form/HearingTicketAddForm.php).
```
> 1024: Fixed initialization error

- CHANGELOG.md
> Release 4.2.0

- CHANGELOG.md
> Release 4.2.1

- CHANGELOG.md
> Release 4.2.2

- CHANGELOG.md
- web/themes/custom/hoeringsportal/assets/js/icons.js
- web/themes/custom/hoeringsportal/templates/block/block--system-menu-block.html.twig
- web/themes/custom/hoeringsportal/templates/content/node--citizen-proposal--teaser.html.twig
- web/themes/custom/hoeringsportal/templates/content/node--list-display.html.twig
- web/themes/custom/hoeringsportal/templates/content/node--project-main-page--teaser.html.twig
- web/themes/custom/hoeringsportal/templates/content/node--public-meeting--teaser.html.twig
- web/themes/custom/hoeringsportal/templates/content/node--static-page--teaser.html.twig
- web/themes/custom/hoeringsportal/templates/content/node--teaser.html.twig
- web/themes/custom/hoeringsportal/templates/field/field--dynamic-block-field--node-project-timeline.html.twig
- web/themes/custom/hoeringsportal/templates/field/field--field-itk-media-mime-type.html.twig
- web/themes/custom/hoeringsportal/templates/field/field--node--field-video--project.html.twig
- web/themes/custom/hoeringsportal/templates/field/field--paragraph--field-external-link--projekt-billede-galleri.html.twig
- web/themes/custom/hoeringsportal/templates/form/form--search-block-form.html.twig
- web/themes/custom/hoeringsportal/templates/layout/html.html.twig
- web/themes/custom/hoeringsportal/templates/misc/itk-pretix-date-entry.html.twig
- web/themes/custom/hoeringsportal/templates/navigation/pager.html.twig
- web/themes/custom/hoeringsportal/templates/newsletter-bottom-link.html.twig
- web/themes/custom/hoeringsportal/templates/node/_node--project-main-page--list-display.html.twig
https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/1353
> Fontawesome: Use local i2svg replace. Update icons. Add missing icons.

- CHANGELOG.md
> Release 4.4.0

- CHANGELOG.md
- config/sync/core.entity_form_display.node.hearing.default.yml
- config/sync/core.entity_view_display.node.hearing.default.yml
- config/sync/core.entity_view_display.node.hearing.hearing_ticket_add.yml
- config/sync/core.entity_view_display.node.hearing.hearing_ticket_view.yml
- config/sync/core.entity_view_display.node.hearing.list_display.yml
- config/sync/core.entity_view_display.node.hearing.teaser.yml
- config/sync/field.field.node.hearing.field_delete_date.yml
- config/sync/field.storage.node.field_delete_date.yml
- documentation/localDevelopment.md
- web/modules/custom/hoeringsportal_data/README.md
- web/modules/custom/hoeringsportal_data/hoeringsportal_data.services.yml
- web/modules/custom/hoeringsportal_data/src/Drush/Commands/DrushCommands.php
- web/modules/custom/hoeringsportal_data/src/Helper/HearingHelper.php
- web/modules/custom/hoeringsportal_deskpro/hoeringsportal_deskpro.install
- web/modules/custom/hoeringsportal_deskpro/hoeringsportal_deskpro.module
- web/modules/custom/hoeringsportal_deskpro/src/Plugin/Block/HearingTicketsBlock.php
- web/modules/custom/hoeringsportal_deskpro/src/Service/HearingHelper.php
- web/modules/custom/hoeringsportal_deskpro/templates/block/hoeringsportal-hearing-tickets.html.twig
- web/modules/custom/hoeringsportal_hearing/modules/hoeringsportal_hearing_fixtures/src/Fixture/HearingFixture.php
- web/themes/custom/hoeringsportal/assets/js/icons.js
https://leantime.itkdev.dk/?tab=timesheet#/tickets/showTicket/2288
Add message when hearing tickets is deleted.
> 2288: Show deleted tickets message after delete_date has passed

- CHANGELOG.md
> Release 4.6.0

- CHANGELOG.md
- config/sync/user.role.editor.yml
- config/sync/views.settings.yml
- web/sites/default/settings.php
https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=2971#/tickets/showTicket/2971
https://freescout.itkdev.dk/conversation/96
* Lets editor edit “Published on” (to fix dates erroneously set to “now”[^1])
* Cleans up view settings (see https://www.drupal.org/project/drupal/issues/3450203 for details)
* Excludes Masquerade module from configuration synchronization
[^1]: The jury is still out on what's causing the issue
> Publication dates

- CHANGELOG.md
- web/themes/custom/hoeringsportal/assets/css/_base.scss
- web/themes/custom/hoeringsportal/templates/layout/region--header.html.twig
https://leantime.itkdev.dk/dashboard/home?tab=ticketdetails#/tickets/showTicket/1674
Avoid navbar jumping when scrolling.
> 1674: Fix jumping navbar when scrolled

- CHANGELOG.md
- Taskfile.yml
- documentation/localDevelopment.md
- web/modules/custom/hoeringsportal_base_fixtures/assets/page_map.yaml
- web/modules/custom/hoeringsportal_base_fixtures/src/Fixture/MapFixture.php
- web/modules/custom/hoeringsportal_config_settings/src/Form/ItkGeneralSettingsForm.php
<https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=3534#/tickets/showTicket/3534>
* Updated tasks
* Allowed paths in site settings
* Updated map page fixture
> Miscellaneous

- CHANGELOG.md
- web/themes/custom/hoeringsportal/assets/js/icons.js
https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/3641
Add missing arrow
> 3641: Add missing icon

- .docker/pretix/dumps/pretix.sql
- CHANGELOG.md
- web/modules/custom/hoeringsportal_base_fixtures/hoeringsportal_base_fixtures.services.yml
- web/modules/custom/hoeringsportal_base_fixtures/src/Fixture/AbstractConfigFixture.php
- web/modules/custom/hoeringsportal_base_fixtures/src/Fixture/AbstractTaxonomyTermFixture.php
- web/modules/custom/hoeringsportal_base_fixtures/src/Fixture/MenuItemFixture.php
- web/modules/custom/hoeringsportal_base_fixtures/src/Fixture/NodeFixture.php
- web/modules/custom/hoeringsportal_base_fixtures/src/Fixture/PretixConfigFixture.php
- web/modules/custom/hoeringsportal_base_fixtures/src/Fixture/PublicMeetingFixture.php
- web/modules/custom/hoeringsportal_base_fixtures/src/Fixture/TermAreaFixture.php
- web/modules/custom/hoeringsportal_base_fixtures/src/Fixture/TermHearingTypeFixture.php
- web/modules/custom/hoeringsportal_base_fixtures/src/Fixture/TermMediaLibraryFixture.php
- web/modules/custom/hoeringsportal_base_fixtures/src/Fixture/TermTagFixture.php
- web/modules/custom/hoeringsportal_base_fixtures/src/Fixture/TermTimelineItemFixture.php
- web/modules/custom/hoeringsportal_base_fixtures/src/Fixture/TermTypeFixture.php
- web/modules/custom/hoeringsportal_project/modules/hoeringsportal_project_fixtures/hoeringsportal_project_fixtures.services.yml
- web/modules/custom/hoeringsportal_project/modules/hoeringsportal_project_fixtures/src/Fixture/ProjectCategoryFixture.php
- web/modules/custom/hoeringsportal_project/modules/hoeringsportal_project_fixtures/src/Fixture/PublicMeetingLandingPageFixture.php
- web/modules/custom/hoeringsportal_public_meeting/hoeringsportal_public_meeting.module
<https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=3689#/tickets/showTicket/3689>
* Cleans up "Public meeting" fixtures and dependencies
> Cleaned up fixtures

- .woodpecker/deployment.yml
- CHANGELOG.md
- config/sync/core.entity_view_display.node.hearing.hearing_ticket_add.yml
- config/sync/core.entity_view_display.node.hearing.hearing_ticket_view.yml
<https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=3745#/tickets/showTicket/3745>
- **3745: Hid deletion date form display. Moved social links.**
- **3745: Forced Drush command to actually do something**
Please include a short description of the suggested change and the reasoning behind the approach you have chosen.
> Fixed hearing reply cleanup

- CHANGELOG.md
> Release 4.6.2

- CHANGELOG.md
- Taskfile.yml
- translations/custom-translations.da.po
- web/modules/custom/hoeringsportal_data/hoeringsportal_data.install
- web/themes/custom/hoeringsportal/translations/hoeringsportal.da.po
Please add a link to the ticket being addressed by this change.
Drupal has some serious issues with pluralization …
* <https://drupalsun.com/eelke/2020/08/17/tale-mistranslated-plurals>
* <https://www.drupal.org/project/drupal/issues/3496223>
This is a pragmatic approach to ~resolve~work around some of them.
> Corrected Danish pluralization

- CHANGELOG.md
- composer.lock
- web/modules/custom/hoeringsportal_data/src/Service/DAWA.php
- web/sites/default/default.settings.php
<https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=3843#/tickets/showTicket/3843>
* Applies securoty updates
> 3843: Security update

- .github/workflows/pr.yaml
- CHANGELOG.md
- docker-compose.server.override.yml
<https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=3949#/tickets/showTicket/3949>
Adds `restart: unless-stopped` on clamav service.
> 3949: Cleaned up docker compose setup

- CHANGELOG.md
> Release 4.6.5

- .github/workflows/pr.yaml
- CHANGELOG.md
> Cleaned up actions

- CHANGELOG.md
- web/modules/custom/hoeringsportal_deskpro/hoeringsportal_deskpro.install
- web/modules/custom/hoeringsportal_deskpro/src/Service/HearingHelper.php
- web/modules/custom/hoeringsportal_deskpro/src/Twig/TwigExtension.php
- web/modules/custom/hoeringsportal_deskpro/templates/block/hoeringsportal-hearing-tickets.html.twig
<https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=3913#/tickets/showTicket/3913>
Builds on <https://github.com/itk-dev/hoeringsportal/pull/454> and fixes a bug and adds “on behalf of” to the ticket list.
> [!CAUTION]
> It's still unclear if this should be released as a hotfix or via merge to `develop`.
Hearing reply details before:
Hearing reply details after:
Hearing reply list item before:
Hearing reply list item after (missing Danish translation):
> 3913: Fixed bug and added "on behalf of” on ticket list

- web/themes/custom/hoeringsportal/templates/content/node--public-meeting--teaser.html.twig
- web/themes/custom/hoeringsportal/templates/content/node--teaser.html.twig
- web/themes/custom/hoeringsportal/templates/field/field--field-pretix-dates.html.twig
Builds on https://github.com/itk-dev/hoeringsportal/pull/451 to clean up a little:
* Cleans up handling of meeting date on public meeting list
* Fixes a couple of typos.
> Public meeting dates on list

- CHANGELOG.md
> Release 4.7.2

- CHANGELOG.md
- web/modules/custom/hoeringsportal_hearing/hoeringsportal_hearing.module
- web/modules/custom/hoeringsportal_hearing/hoeringsportal_hearing.services.yml
- web/modules/custom/hoeringsportal_hearing/src/Helper/FormHelper.php
<https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=4007&tab=timesheet#/tickets/showTicket/4007>
Adds validation of dates on new hearing to make sure that they make some sense.
> Hearing date validation

- CHANGELOG.md
- web/modules/custom/hoeringsportal_citizen_proposal/hoeringsportal_citizen_proposal.routing.yml
Prevents caching of citizen proposal forms.
> Release 4.7.3

- .docker/nginx.conf
- .docker/templates/default.conf.template
- .woodpecker/stg.yml
- CHANGELOG.md
- docker-compose.dev.yml
- docker-compose.override.yml
- docker-compose.redirect.yml
- docker-compose.server.override.yml
- docker-compose.server.yml
- docker-compose.yml
- patches/development/mitid-test-cpr-hack.patch
- web/themes/custom/hoeringsportal/package-lock.json
> Release 4.8.0

- CHANGELOG.md
- config/sync/core.entity_view_display.node.hearing.default.yml
- config/sync/system.site.yml
Hotfix 4.8.1: Fixes placement of “Social buttons”
Before:
After:
> Fixed placement of “Social buttons”

- CHANGELOG.md
- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/user.role.citizen_proposal_editor.yml
<https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=4092#/tickets/showTicket/4092>
Adds View Unpublished module and configuration to allow citizen proposal editors to see and edit unpublished citizen proposals.
> Installed and configured View Unpublished module

- web/modules/custom/hoeringsportal_base_fixtures/hoeringsportal_base_fixtures.info.yml
- web/modules/custom/hoeringsportal_base_fixtures/hoeringsportal_base_fixtures.services.yml
- web/modules/custom/hoeringsportal_base_fixtures/src/Fixture/LandingPageFixture.php
Build on the excellent work in https://github.com/itk-dev/hoeringsportal/pull/477 and sets the generate front page as actual site front page.
> Set frontpage in fixture

- CHANGELOG.md
> Release 4.8.3

- CHANGELOG.md
- config/sync/views.view.citizen_proposal_support.yml
- config/sync/views.view.content.yml
- config/sync/views.view.user_admin_people.yml
Cleans up exports by making the formats and filenames consistent.
> Made exports consistent

- CHANGELOG.md
- config/sync/core.entity_form_display.node.landing_page.default.yml
- config/sync/core.entity_form_display.paragraph.content_promotion.default.yml
- config/sync/core.entity_form_display.paragraph.link.default.yml
- config/sync/core.entity_view_display.paragraph.content_promotion.default.yml
- config/sync/core.entity_view_display.paragraph.link.default.yml
- config/sync/field.field.node.landing_page.field_section.yml
- config/sync/field.field.paragraph.content_promotion.field_abstract.yml
- config/sync/field.field.paragraph.content_promotion.field_button.yml
- config/sync/field.field.paragraph.content_promotion.field_lead.yml
- config/sync/field.field.paragraph.content_promotion.field_paragraph_image.yml
- config/sync/field.field.paragraph.content_promotion.field_title.yml
- config/sync/field.field.paragraph.link.field_button_variant.yml
- config/sync/field.storage.paragraph.field_button.yml
- config/sync/field.storage.paragraph.field_button_variant.yml
- config/sync/field.storage.paragraph.field_lead.yml
- config/sync/paragraphs.paragraphs_type.content_promotion.yml
- web/modules/custom/hoeringsportal_base_fixtures/hoeringsportal_base_fixtures.services.yml
- web/modules/custom/hoeringsportal_base_fixtures/src/Fixture/AboutPageFixture.php
- web/modules/custom/hoeringsportal_base_fixtures/src/Fixture/LandingPageFixture.php
- web/modules/custom/hoeringsportal_base_fixtures/src/Fixture/MenuItemFixture.php
- web/modules/custom/hoeringsportal_base_fixtures/src/Fixture/PublicMeetingFixture.php
- web/themes/custom/hoeringsportal/assets/css/hoeringsportal.scss
- web/themes/custom/hoeringsportal/assets/css/module/_paragraph-content-promotion.scss
- web/themes/custom/hoeringsportal/assets/css/module/_paragraph-link.scss
- web/themes/custom/hoeringsportal/templates/paragraph/paragraph--content-promotion.html.twig
- web/themes/custom/hoeringsportal/templates/paragraph/paragraph--link.html.twig
https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=3996#/tickets/showTicket/3996
Create new paragraph section to promote content on other pages.
> Feature - Paragraph content promotion

- CHANGELOG.md
- config/sync/user.role.public_meeting_editor.yml
Fixes media permissions for public meeting editor
> Release 4.8.5

- CHANGELOG.md
- composer.json
- composer.lock
https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=4208#/tickets/showTicket/4208
Security update and release 4.8.6
* Updates Drupal core (`composer update "drupal/core-*" --with-all-dependencies`)
* Updates contrib modules (`composer update --patch-only`)
* Removes `bower-asset/jqueryui-touch-punch`
> Security update

- CHANGELOG.md
- documentation/localDevelopment.md
- web/modules/custom/hoeringsportal_deskpro/src/Service/DeskproService.php
- web/modules/custom/hoeringsportal_deskpro/src/Service/mock/languages.yaml
- web/modules/custom/hoeringsportal_deskpro/src/Service/mock/ticket_custom_fields.yaml
- web/modules/custom/hoeringsportal_deskpro/src/Service/mock/ticket_custom_fields/2.yaml
- web/modules/custom/hoeringsportal_deskpro/templates/block/hoeringsportal-hearing-ticket-author.html.twig
- web/modules/custom/hoeringsportal_hearing/modules/hoeringsportal_hearing_fixtures/hoeringsportal_hearing_fixtures.info.yml
- web/modules/custom/hoeringsportal_hearing/modules/hoeringsportal_hearing_fixtures/hoeringsportal_hearing_fixtures.services.yml
- web/modules/custom/hoeringsportal_hearing/modules/hoeringsportal_hearing_fixtures/src/Fixture/HearingFixture.php
Please add a link to the ticket being addressed by this change.
* Adds hearing reply fixtures
* Fixes ticket auther template
> Hearing reply fixtures

- .env
- docker-compose.server.yml
- docker-compose.yml
Sets some useful docker compose variables.
> docker compose setup

- CHANGELOG.md
- Taskfile.yml
- docker-compose.override.yml
- documentation/localDevelopment.md
https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=4242#/tickets/showTicket/4242
Optimizes the development setup.
> Optimized development setup

- CHANGELOG.md
- translations/custom-translations.da.po
https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=4264#/tickets/showTicket/4264
* Updates Danish translations of names of days and months
* Add missing translation (exported from production site)
> Danish translations

- CHANGELOG.md
- composer.json
- composer.lock
Please add a link to the ticket being addressed by this change.
* Updates composer/installers to add PHP 8.4 support (cf. https://github.com/composer/installers/issues/544#issuecomment-2697412822)
* Updates drupal/content_fixtures (cf. https://www.drupal.org/project/content_fixtures/issues/3498162)
> Composer updates

- CHANGELOG.md
- config/sync/user.role.project_editor.yml
- web/modules/custom/hoeringsportal_project/modules/hoeringsportal_project_fixtures/src/Fixture/ProjectMainPageFixture.php
https://github.com/itk-dev/deltag.aarhus.dk/issues/504
- Lets project editor edit URL alias
- Updates project fixture
> 504 enable url alias permissions for project editor role

- CHANGELOG.md
- web/themes/custom/hoeringsportal/package-lock.json
- web/themes/custom/hoeringsportal/package.json
<https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=4721#/tickets/showTicket/4721>
Updates npm packages to resolve issues reported by `npm audit`
> npm package update

- CHANGELOG.md
- config/sync/user.role.administrator.yml
- config/sync/user.role.hearing_editor.yml
- config/sync/user.role.project_editor.yml
- config/sync/user.role.public_meeting_editor.yml
Resolves #512 
See commit messages for more info.
> Add icon entity browser permissions

- CHANGELOG.md
- composer.json
- composer.lock
- config/sync/core.entity_form_display.node.hearing.default.yml
- config/sync/core.extension.yml
- web/modules/custom/hoeringsportal_public_meeting/src/Helper/PublicMeetingHelper.php
- web/themes/custom/hoeringsportal/templates/content/node--hearing--teaser.html.twig
- web/themes/custom/hoeringsportal/templates/content/node--project-main-page--teaser.html.twig
- web/themes/custom/hoeringsportal/templates/content/node--public-meeting--teaser.html.twig
- web/themes/custom/hoeringsportal/templates/ds/ds-2col-stacked--node-hearing.html.twig
Closes #521 
Fixes support issues from #521 
Text length:
Public meeting times:
> 521 supportfeedback after release 4100

- CHANGELOG.md
- composer.json
- composer.lock
- config/sync/config_ignore.settings.yml
- config/sync/core.extension.yml
- config/sync/user.role.administrator.yml
<https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=4897#/tickets/showTicket/4897>
A hotfix release to add the [Site Status Message](https://www.drupal.org/project/site_status_message) module.
> 4897: Added Site Status Message module

- CHANGELOG.md
- config/sync/core.extension.yml
- config/sync/toolbar_visibility.default_config.yml
- config/sync/toolbar_visibility.settings.yml
- web/modules/custom/hoeringsportal_misc/hoeringsportal_misc.info.yml
- web/modules/custom/hoeringsportal_misc/hoeringsportal_misc.install
- web/modules/custom/hoeringsportal_misc/hoeringsportal_misc.module
https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=4850#/tickets/showTicket/4850
Replaces the (unmaintained?) [Toolbar Visibility](https://www.drupal.org/project/toolbar_visibility) module with a little bit of custom logic.
> [!NOTE]
> `drupal/toolbar_visibility` has not yet been removed from `composer.json` ­ we must try to remember to do this later …
> Added custom toolbar visibility logic

- CHANGELOG.md
- web/themes/custom/hoeringsportal/package-lock.json
- web/themes/custom/hoeringsportal/templates/components/base-card.html.twig
- web/themes/custom/hoeringsportal/templates/content/node--hearing--teaser.html.twig
- web/themes/custom/hoeringsportal/templates/content/node--public-meeting--teaser.html.twig
https://leantime.itkdev.dk/_#/tickets/showTicket/5121
* Handles missing (empty) dates in teasers.
* Applies security update to npm package
> 5121: Fixed handling of missing dates

- CHANGELOG.md
- web/modules/custom/hoeringsportal_base_fixtures/src/Fixture/PublicMeetingFixture.php
- web/modules/custom/hoeringsportal_content_blocks/templates/hoeringsportal-meeting-warning.html.twig
- web/modules/custom/hoeringsportal_public_meeting/src/Helper/PublicMeetingHelper.php
- web/modules/custom/hoeringsportal_public_meeting/templates/hoeringsportal-public-meeting-summary.html.twig
https://leantime.itkdev.dk/_#/tickets/showTicket/5227
* Restored non-pretix meeting summary
* Updated public meeting fixtures
* Added spacing (bonus)
Before:
After:
Before:
After:
> 5227: Public meeting summary
