- web/modules/custom/hoeringsportal_content_blocks/templates/hoeringsportal-meeting-warning.html.twig
- web/modules/custom/hoeringsportal_public_meeting/hoeringsportal_public_meeting.module
- web/themes/custom/hoeringsportal/templates/content/field-group-html-element--group-signup.html.twig
- Quick fix of twig strict comparison error
- Added check for signup selection before grabbing stuff from pretix field.
- Added custom validation handler to ensure a last_meeting_time is always available for views.
https://jira.itkdev.dk/browse/HRIN-450
> HRIN-450: Added custom validate function

- config/sync/core.entity_form_display.node.public_meeting.default.yml
- config/sync/core.entity_view_display.node.public_meeting.default.yml
- config/sync/core.entity_view_display.node.public_meeting.teaser.yml
- config/sync/field.field.node.public_meeting.field_pretix_dates.yml
- config/sync/field.field.node.public_meeting.field_pretix_event_settings.yml
- config/sync/field.storage.node.field_pretix_dates.yml
- config/sync/field.storage.node.field_pretix_event_settings.yml
- web/modules/custom/hoeringsportal_public_meeting/hoeringsportal_public_meeting.module
https://jira.itkdev.dk/browse/HRIN-463
Updates config to match changes in https://github.com/itk-dev/itk_pretix_d8/pull/12.
A manual update of the database is required to make everything work after doing this (the lazy programmer hasn't yet added update hooks):
```sql
update config set data = replace(data, 's:22:"pretix_date_field_type"', 's:11:"pretix_date"') where data like '%s:22:"pretix_date_field_type"%'\G
update config set data = replace(data, 's:32:"pretix_event_settings_field_type"', 's:21:"pretix_event_settings"') where data like '%s:32:"pretix_event_settings_field_type"%'\G
update key_value set value = replace(value, 's:22:"pretix_date_field_type"', 's:11:"pretix_date"') where value like '%s:22:"pretix_date_field_type"%'\G
update key_value set value = replace(value, …
```
> HRIN-463: Updated field type, widget and formatter ids

- web/modules/custom/hoeringsportal_project_timeline/src/Plugin/Block/ProjectTimeline.php
- web/modules/custom/hoeringsportal_public_meeting/hoeringsportal_public_meeting.module
https://jira.itkdev.dk/browse/HRIN-471
Depends on changes in https://github.com/itk-dev/itk_pretix_d8/pull/15 and manually updating the database:
```sql
/* Create new date columns */
ALTER TABLE node__field_pretix_dates
ADD COLUMN field_pretix_dates_time_from_value VARCHAR(20) NOT NULL,
ADD COLUMN field_pretix_dates_time_to_value VARCHAR(20) NOT NULL;
ALTER TABLE node_revision__field_pretix_dates
ADD COLUMN field_pretix_dates_time_from_value VARCHAR(20) NOT NULL,
ADD COLUMN field_pretix_dates_time_to_value VARCHAR(20) NOT NULL;
/* Copy date values */
UPDATE node__field_pretix_dates
SET field_pretix_dates_time_from_value = REPLACE(SUBSTRING(CONVERT_TZ(SUBSTRING(field_pretix_dates_time_from, 1, 19), SUBSTRING(field_pretix_dates_time_from, 21), 'UTC'), 1, 19), ' ', 'T'), …
```
> HRIN-471: Updated handling of pretix dates

- composer.json
- composer.lock
https://jira.itkdev.dk/browse/HRIN-671
Fixes
```
Drupal\Core\Security\UntrustedCallbackException: Render #post_render callbacks must be methods of a class that implements \Drupal\Core\Security\TrustedCallbackInterface or be an anonymous function. The callback was Drupal\entity_browser\Plugin\views\display\EntityBrowser::postRender. See https://www.drupal.org/node/2966725 in Drupal\Core\Render\Renderer->doTrustedCallback() (line 96 of core/lib/Drupal/Core/Security/DoTrustedCallbackTrait.php). 
```
(cf. https://www.drupal.org/node/2966725)
See “8.x-2.x branch information” on https://www.drupal.org/project/entity_browser.
> HRIN-671: Updated entity_browser module

- web/themes/custom/hoeringsportal/hoeringsportal.libraries.yml
- web/themes/custom/hoeringsportal/package.json
- web/themes/custom/hoeringsportal/webpack.config.js
- web/themes/custom/hoeringsportal/yarn.lock
https://jira.itkdev.dk/browse/HRIN-717
This pr updates the themes dependencies to work with new cpu architecture on mac.
Does not affect anything visually.
> HRIN-717: Dep. updates for new architecture.

- CHANGELOG.md
- composer.json
- composer.lock
- web/modules/custom/aarhus_hero/src/State/BaseConfig.php
- web/modules/custom/hoeringsportal_base_fixtures/src/Helper/Helper.php
- web/modules/custom/hoeringsportal_config_settings/src/Form/ItkGeneralSettingsForm.php
- web/modules/custom/hoeringsportal_content_blocks/src/Plugin/Block/HearingTypeMoreInfo.php
- web/modules/custom/hoeringsportal_content_blocks/src/Plugin/Block/MeetingWarning.php
- web/modules/custom/hoeringsportal_data/hoeringsportal_data.module
- web/modules/custom/hoeringsportal_data/src/Plugin/Field/FieldFormatter/LocalplanDefaultFormatter.php
- web/modules/custom/hoeringsportal_data/src/Plugin/Field/FieldFormatter/MapDefaultFormatter.php
- web/modules/custom/hoeringsportal_data/src/Plugin/Field/FieldType/MapItem.php
- web/modules/custom/hoeringsportal_deskpro/hoeringsportal_deskpro.install
- web/modules/custom/hoeringsportal_deskpro/src/Form/HearingTicketAddForm.php
- web/modules/custom/hoeringsportal_deskpro/src/State/DeskproConfig.php
- web/modules/custom/hoeringsportal_forms/src/Plugin/views/filter/NodeIndexNid.php
- web/modules/custom/hoeringsportal_hearing/hoeringsportal_hearing.module
- web/modules/custom/hoeringsportal_project_timeline/hoeringsportal_project_timeline.install
- web/modules/custom/hoeringsportal_project_timeline/src/Plugin/Block/ProjectTimeline.php
- web/modules/custom/hoeringsportal_public_meeting/hoeringsportal_public_meeting.module
- web/modules/custom/hoeringsportal_public_meeting/src/Plugin/Block/PublicMeetingSummaryBlock.php
- web/modules/custom/itk_admin/src/State/BaseConfig.php
- web/modules/custom/itk_admin_links/src/Plugin/Block/ItkAdminLinks.php
- web/themes/custom/hoeringsportal/hoeringsportal.theme
https://jira.itkdev.dk/browse/HRIN-740
Applies patch <https://www.drupal.org/project/drupal/issues/3222107#comment-15048236> to make media stuff work.
> HRIN-740: Applied a patch

- web/modules/custom/hoeringsportal_citizen_proposal/hoeringsportal_citizen_proposal.install
Fixes creation of index in update hook.
Using `hoeringsportal_citizen_proposal_schema()` to get the table info may break if changes are made to what `hoeringsportal_citizen_proposal_schema` returns.
> Fix update hook

- CHANGELOG.md
- composer.lock
- web/modules/custom/hoeringsportal_openid_connect/composer.json
https://jira.itkdev.dk/browse/SERV-699
* Bumps `itk-dev/openid-connect` to [3.1](https://github.com/itk-dev/openid-connect/releases/tag/3.1.0)
> SERV-699: Bumped itk-dev openid-connect version

- CHANGELOG.md
- config/sync/core.entity_view_display.node.citizen_proposal.default.yml
https://jira.itkdev.dk/browse/FORSLAG-79
Hides field from display.
> FORSLAG-79: Hid “Author email display” from display

- CHANGELOG.md
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormSupport.php
https://jira.itkdev.dk/browse/FORSLAG-76
Removes email from citizen proposal support form.
> FORSLAG-76: Removed email from citizen proposal support form

- CHANGELOG.md
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalAdminForm.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormBase.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormSupport.php
https://jira.itkdev.dk/browse/FORSLAG-86
Adds “Redirect URL after a proposal has been supported” to admin settings – and uses it to redirect a citizen after supporting a proposal.
> FORSLAG-86: Added support redirect URL

- config/sync/user.role.citizen_proposal_editor.yml
https://jira.itkdev.dk/browse/FORSLAG-74
Adds missing permission. Doesn't update the change log.
> FORSLAG-74: Allowed citizen proposal editors to use Email HTML text format

- CHANGELOG.md
- config/sync/core.entity_form_display.node.citizen_proposal.default.yml
- config/sync/core.entity_view_display.node.citizen_proposal.citizen_proposal_add.yml
- config/sync/core.entity_view_display.node.citizen_proposal.citizen_proposal_approval.yml
- config/sync/core.entity_view_display.node.citizen_proposal.default.yml
- config/sync/core.entity_view_display.node.citizen_proposal.list_display.yml
- config/sync/core.entity_view_display.node.citizen_proposal.teaser.yml
- config/sync/field.field.node.citizen_proposal.field_author_allow_email.yml
- config/sync/field.storage.node.field_author_allow_email.yml
- config/sync/views.view.citizen_proposal_support.yml
- web/modules/custom/hoeringsportal_citizen_proposal/hoeringsportal_citizen_proposal.install
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalAdminForm.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormAdd.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormApprove.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormBase.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormSupport.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Helper/Helper.php
https://jira.itkdev.dk/browse/FORSLAG-77
Adds “Allow email”, i.e. “I accept receiving email from you”, checkbox on both proposal create and support form.
> FORSLAG-77: More checkboxes

- CHANGELOG.md
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalAdminForm.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormAdd.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormApprove.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormBase.php
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormSupport.php
https://jira.itkdev.dk/browse/FORSLAG-101
> FORSLAG-101: Generalized handling of form surveys. Added survey to support form.

- CHANGELOG.md
- web/modules/custom/hoeringsportal_citizen_proposal/modules/hoeringsportal_citizen_proposal_fixtures/src/Fixture/CitizenProposalFixture/citizen_proposal_admin_form_values.yaml
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormAdd.php
- web/themes/custom/hoeringsportal/assets/css/module/_proposal.scss
https://jira.itkdev.dk/browse/FORSLAG-102
Makes display of checkboxes consistent.
Before:
After:
> FORSLAG-102: Cleaned up display of checkboxes

- CHANGELOG.md
- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/editor.editor.hearing_description.yml
- config/sync/field.field.node.hearing.field_description.yml
- config/sync/filter.format.hearing_description.yml
- config/sync/user.role.authenticated.yml
- web/modules/custom/hoeringsportal_data/src/Plugin/Field/FieldWidget/MapDefaultWidget.php
- web/modules/custom/hoeringsportal_hearing/assets/css/gis-minimap.css
- web/modules/custom/hoeringsportal_hearing/hoeringsportal_hearing.install
- web/modules/custom/hoeringsportal_hearing/hoeringsportal_hearing.libraries.yml
- web/modules/custom/hoeringsportal_hearing/hoeringsportal_hearing.module
- web/modules/custom/hoeringsportal_hearing/hoeringsportal_hearing.services.yml
- web/modules/custom/hoeringsportal_hearing/modules/hoeringsportal_hearing_fixtures/src/Fixture/HearingFixture.php
- web/modules/custom/hoeringsportal_hearing/src/TokenHelper.php
https://jira.itkdev.dk/browse/HRIN-767
Adds GIS map token for use in hearing descriptions.
We have an issue with “plandata” that is used somewhere:
<https://geoserver.plandata.dk/geoserver/wfs?request=GetFeature&typeNames=pdk%3Alokalplan&srsName=EPSG%3A4326&outputFormat=application%2Fjson&cql_filter=planid%20IN%20%289417152%29&servicename=wfs&service=wfs&version=2.0.0>:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 https://geoserver.plandata.dk/geoserver/schemas/ows/1.1.0/owsAll.xsd">
<ows:Exception exceptionCode="InvalidParameterValue" locator="typeName"> …
```
> HRIN-767: Added GIS map token

- CHANGELOG.md
- web/themes/custom/hoeringsportal/templates/components/header.html.twig
https://leantime.itkdev.dk/#/tickets/showTicket/1152
Fixes issue with the `without` filter being used on non-array values.
> 1152: Fixed rendering of headers

- CHANGELOG.md
- config/sync/core.extension.yml
- config/sync/views.view.all_projects.yml
- web/themes/custom/hoeringsportal/templates/form/views-exposed-form.html.twig
- web/themes/custom/hoeringsportal/templates/layout/region--header.html.twig
https://leantime.itkdev.dk/dashboard/home?tab=timesheet#/tickets/showTicket/1145
Result after removing category filter
> Project page remove category filter

- .docker/nginx.conf
- .docker/templates/default.conf.template
- CHANGELOG.md
- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/log_stdout.settings.yml
- docker-compose.dev.yml
- docker-compose.redirect.yml
- docker-compose.server.yml
- docker-compose.yml
<https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/1449>
- 1449: Updated docker compose setup
- 1449: Enabled and configured log_stdout
> log_stdout

- CHANGELOG.md
- composer.json
- composer.lock
- config/sync/clamav.settings.yml
- config/sync/core.extension.yml
- docker-compose.override.yml
- docker-compose.server.override.yml
Ticket: https://leantime.itkdev.dk/dashboard/home?tab=ticketdetails#/tickets/showTicket/1451
> Added clam-av module and settings

- CHANGELOG.md
- config/sync/clamav.settings.yml
- web/themes/custom/hoeringsportal/templates/ds/ds-1col.html.twig
- web/themes/custom/hoeringsportal/templates/field/field--paragraph--teaser-row.html.twig
- web/themes/custom/hoeringsportal/templates/paragraph/paragraph--content-block.html.twig
- web/themes/custom/hoeringsportal/templates/paragraph/paragraph--files.html.twig
- web/themes/custom/hoeringsportal/templates/paragraph/paragraph--info-box.html.twig
- web/themes/custom/hoeringsportal/templates/paragraph/paragraph--teaser-row.html.twig
- web/themes/custom/hoeringsportal/templates/paragraph/paragraph--text-aside-blocks-2-column.html.twig
- web/themes/custom/hoeringsportal/templates/paragraph/paragraph.html.twig
https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/1545
Add space between paragraphs
Før:
Efter:
> Landing page paragraph spacing

- CHANGELOG.md
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormBase.php
https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/1983
Drupal adds a `placeholder` class on text marked up with `%placeholder` (using [`t`](https://api.drupal.org/api/drupal/core%21includes%21bootstrap.inc/function/t/11.x)), but the `placeholder` class is styled by Bootstrap (https://getbootstrap.com/docs/5.3/components/placeholders/#how-it-works) in a way that we do not want.
Before:
After:
> 1983: Removed .placeholder markup

- CHANGELOG.md
- docker-compose.server.override.yml
https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/2293
Our configuration of nginx's [`client_max_body_size`](https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) does not match PHP's [`upload_max_filesize`](https://www.php.net/manual/en/ini.core.php#ini.upload-max-filesize) and therefore huge images (with a size over 5 MB) cannot be uploaded.
> Increase nginx max body size

- CHANGELOG.md
- web/modules/custom/hoeringsportal_deskpro/README.md
<https://leantime.itkdev.dk//dashboard/home#/tickets/showTicket/2456>
> Added more test setup stuff

- CHANGELOG.md
- config/sync/field.field.node.hearing.field_delete_date.yml
- documentation/localDevelopment.md
- web/modules/custom/hoeringsportal_data/README.md
- web/modules/custom/hoeringsportal_data/hoeringsportal_data.services.yml
- web/modules/custom/hoeringsportal_data/src/Drush/Commands/DrushCommands.php
- web/modules/custom/hoeringsportal_data/src/Helper/HearingHelper.php
- web/modules/custom/hoeringsportal_deskpro/hoeringsportal_deskpro.install
- web/modules/custom/hoeringsportal_deskpro/hoeringsportal_deskpro.module
- web/modules/custom/hoeringsportal_deskpro/src/Plugin/Block/HearingTicketsBlock.php
- web/modules/custom/hoeringsportal_deskpro/src/Service/HearingHelper.php
- web/modules/custom/hoeringsportal_deskpro/templates/block/hoeringsportal-hearing-tickets.html.twig
- web/modules/custom/hoeringsportal_hearing/modules/hoeringsportal_hearing_fixtures/src/Fixture/HearingFixture.php
https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/2456
Builds on the excellent work in https://github.com/itk-dev/hoeringsportal/pull/418.
* Adds Drush command to actually delete replies from hearings with a “delete date” in the past.
* Removes unused database table (`hoeringsportal_deskpro_deskpro_data`)
> 2288: Deleted hearing replies after delete_date is passed

- CHANGELOG.md
- web/modules/custom/hoeringsportal_citizen_proposal/src/Form/ProposalFormSupport.php
https://leantime.itkdev.dk/dashboard/home?tab=ticketdetails#/tickets/showTicket/1606
Moves form fields around and makes “Name” visible (and required) only when requesting emails.
Before:
After:
> 1606: Made supporter name optional

- CHANGELOG.md
- Taskfile.yml
- documentation/Testing.md
- documentation/localDevelopment.md
perhaps this one: https://leantime.itkdev.dk/#/tickets/showTicket/2381
Add build assets to`TaskFile.yml`
> add build assets task

- .markdownlint.jsonc
- CHANGELOG.md
- config/sync/openid_connect.client.generic.yml
- docker-compose.oidc.yml
- documentation/openIdConnect.md
- Add config for oidc and 
- Add documentation of users (some of it stolen from [ai-screening](https://github.com/itk-dev/ai-screening/blob/df0ffe693a061daa50e89187db81c9c819a8f126/docs/Development.md#L16)
- Rename `department1-editor` to `department1-admin` as it was in the group "administrator"
> add usable config values for oidc

- CHANGELOG.md
- web/modules/custom/hoeringsportal_data/src/Controller/Api/ApiController.php
- web/modules/custom/hoeringsportal_data/src/Controller/Api/GeoJSON/HearingController.php
- web/modules/custom/hoeringsportal_data/src/Controller/Api/GeoJSON/PublicMeetingController.php
- web/modules/custom/hoeringsportal_data/src/Controller/Api/V2/GeoJSON/HearingController.php
- web/modules/custom/hoeringsportal_data/src/Helper/GeoJsonHelper.php
<https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=3534#/tickets/showTicket/3534>
* Builds on improvements made in <https://github.com/itk-dev/hoeringsportal/pull/429> by adding caching of API responses
* Adds additional properties in GeoJSON API to make it possible to skip the deltag.aarhus.dk → Carto → deltag.aarhus.dk loop for showing stuff on a map – which we do.
> Cleaned up API and added caching

- CHANGELOG.md
- web/modules/custom/hoeringsportal_deskpro/hoeringsportal_deskpro.install
- web/modules/custom/hoeringsportal_deskpro/src/Form/HearingTicketAddForm.php
- web/modules/custom/hoeringsportal_deskpro/src/Service/DeskproService.php
- web/modules/custom/hoeringsportal_deskpro/src/Service/HearingHelper.php
- web/modules/custom/hoeringsportal_deskpro/src/State/DeskproConfig.php
- web/modules/custom/hoeringsportal_deskpro/src/Twig/TwigExtension.php
- web/modules/custom/hoeringsportal_deskpro/templates/block/hoeringsportal-hearing-tickets.html.twig
<https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=3913#/tickets/showTicket/3913>
Updates person name in Deskpro if email matches an already existing email. If not doing this, the old name will be used for the person posting a hearing reply.
> [!CAUTION]
> It's still unclear if this should be released as a hotfix or via merge to `develop`.
> Update person name in Deskpro on email match

- .github/workflows/pr.yaml
- CHANGELOG.md
Prevents
> Error: API rate limit exceeded for 20.161.78.130. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
when using `arduino/setup-task` (cf.  <https://github.com/arduino/setup-task/tree/56d0cc033e3cecc5f07a291fdd39f29388d21800?tab=readme-ov-file#repo-token>).
> Added token to setup-task

- CHANGELOG.md
- web/modules/custom/itk_admin_links/templates/itk-admin-links-block.html.twig
https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=4223#/tickets/showTicket/4223
Release 4.8.7: Fixes “Log off” URL.
> Fixed “Log off” URL

- CHANGELOG.md
- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/publishcontent.settings.yml
- config/sync/user.role.citizen_proposal_editor.yml
<https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=4297#/tickets/showTicket/4297>
Adds [Publish Content](https://www.drupal.org/project/publishcontent) module and lets citizen proposal editors publish citizen proposals.
> [!NOTE]
> The failing “audit” check has been fixed in https://github.com/itk-dev/hoeringsportal/pull/447 and everything will fall into place when we release and merge a lot of stuff first thing next week.
> Hotfix 4.9.1

- CHANGELOG.md
- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/view_custom_table.tables.yml
- config/sync/views.view.all_citizen_proposals.yml
- config/sync/views.view.citizen_proposal.yml
- config/sync/views.view.citizen_proposal_support.yml
- web/modules/custom/hoeringsportal_citizen_proposal/hoeringsportal_citizen_proposal.info.yml
- web/modules/custom/hoeringsportal_citizen_proposal/hoeringsportal_citizen_proposal.links.task.yml
- web/modules/custom/hoeringsportal_citizen_proposal/hoeringsportal_citizen_proposal.module
- web/modules/custom/hoeringsportal_citizen_proposal/hoeringsportal_citizen_proposal.routing.yml
- web/modules/custom/hoeringsportal_citizen_proposal/src/Helper/Helper.php
https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=4333#/tickets/showTicket/4333
* Fixes a typo (https://github.com/itk-dev/deltag.aarhus.dk/pull/500/commits/c12e3c11ed1ed55131ee4568b5dd91e2ecd73efb)
* Adds citizen proposal overview (view) with count of supporters. Caveat: I'd like to show all citizen proposals, but currently the view shows only proposal with at least one supporter. Some more `hook_views_data` tricks are needed to make this work.
* Removes the [Views Custom Table module](https://www.drupal.org/project/view_custom_table) and implements (some)`hook_views_data` tricks to make custom table data available for views …
> feature/citizen proposal view II
